# Site settings
title: Rasistinen Suomi
email: mikael.brunila@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kaivuri on syksyllä 2015 perustettu tutkiva journalistinen ja akateeminen kollektiivi.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hegemonni.github.io/" # the base hostname & protocol for your site
twitter_username: mikaelbrunila
github_username:  hegemonni
include: ['CartoDB']

# Build settings
markdown: kramdown
